name: fischteinfineart
favicon: null
layout_spectrum: 0.05555813550017774
typography_spectrum: 0.30344379879534245
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.7066234813537449
  lightness: 0.13838570029474795
  saturation: 0.8505549649707973
  rhythmicContrast: 0.9589520674198866
purpose: []
